allowBuilds:
  esbuild: true
  msw: true
  unrs-resolver: true
  babel-plugin-prefix-private-members@https://codeload.github.com/mbraak/babel-plugin-prefix-private-members/tar.gz/bb246e0203359de7ea5f6dd8fbd2e6620274746a: true
minimumReleaseAgeExclude:
  - babel-plugin-prefix-private-members@0.1.0
