import jsonfile from "jsonfile";
import fs from "node:fs";

// Package.json is the single source of truth for the version. Generate
// src/version.ts from it, so that getVersion() cannot drift from the version
// that is published and from the version in the banner of the bundles.

const versionFile = "src/version.ts";

const { version } = jsonfile.readFileSync("package.json");

const contents = `// Generated by config/generateVersion.mjs. Do not edit.
const version = ${JSON.stringify(version)};

export default version;
`;

const current = fs.existsSync(versionFile)
  ? fs.readFileSync(versionFile, "utf8")
  : undefined;

if (current !== contents) {
  fs.writeFileSync(versionFile, contents);
  console.log(`Updated ${versionFile} to ${version}`);
}
